version: "2"

services:
    # Ruby+Rails container
    web:
        build:
            context: .dockerfiles
            dockerfile: Dockerfile.web
            args:
                node_version: 6.7.0
        environment:
            - BUNDLE_APP_CONFIG=/opt/bundle
            - BUNDLE_BIN=/opt/bundle/bin
            - BUNDLE_SILENCE_ROOT_WARNING=1
            - BUNDLE_PATH=/opt/bundle
            - GEM_HOME=/opt/bundle
        volumes:
            - .:/usr/src/app
            - tmp:/usr/src/app/tmp
            - bundle:/opt/bundle
        ports:
            - "3000:3000"

volumes:
    bundle:
    tmp:
